project:
  type: website
  preview:
    port: 7777
    browser: false

website:
  title: "Evolv-ED "
  site-url: "https://www.evolv-ed.net/"
  navbar:
    logo: "/images/logo.png"
    search: true
    left:
      - text: About
        menu:
          - text: "Why?" 
            href: why.qmd
          - href: team.qmd
            text: Contributors 
          - href: material.qmd
            text: "The Material"
      - file: databases.qmd
        text: "Databases"
      - file: software.qmd
        text: "Software"
      - file: examples.qmd
        text: "Practice"
      - text: "Contribute!"
        menu:
        - href: about.qmd
          text: "How?"
        - href: about.qmd
          text: "Guide"
        - href: about.qmd
          text: "Get in touch!"
    right:
      - href: "https://integrated-record.github.io/"
        text: IRAL 
      - icon: github
        href: https://github.com/integrated
      - icon: twitter
        href: https://twitter.com/learn_evolved
        
  sidebar:
    - title: "Databases"
      style: "docked"
#      background: "#ffffff"
      collapse-level: 2 
      contents:
        - href: "databases.qmd"
          text: "**Databases**"
        - section: "Biology"
          contents:
          - href: "databases/organism_distribution.qmd"
            text: "Organism Distribution"
            contents:
              - href: "databases/registry/pbdb.qmd"
                text: "Paleobiology Database"
          - href: "databases/taxonomy.qmd"
            text: "Taxonomy"
          - href: "databases/trait_databases.qmd"
            text: "Traits"
          - href: "databases/morphology.qmd"
            text: "Organism morphology"
          - href: "databases/phylogenies.qmd"
            text: "Phylogenies"
          - href: "databases/interaction.qmd"
            text: "Biotic Interaction"
          - href: "databases/bioregionalization.qmd"
            text: "Bioregionalization"
        - section: "Geology/Geography"
          contents:
          - href: "databases/paleogeography.qmd"
            text: "Paleogeography"
          - href: "databases/modern_geography.qmd"
            text: "Modern Geography"
          - href: "databases/stratigraphy.qmd"
            text: "Stratigraphy"
          - href: "databases/cultural.qmd"
            text: "Anthropogenic"
    - title: "Software"
      style: "docked"
      collapse-level: 3
      contents:
        - file: software.qmd
          text: "**Software**"
        - section: Publishing Tools
          file: software/R.qmd
        - section: Programming 
          contents:
          - section: R
            file: software/R.qmd
            contents:
            - section: Ecology 
              contents:
              - file: software/R/eco/iNEXT.qmd
                text: iNEXT
            - section: Geology/Paleontology
              contents:
              - file: software/R/geo_paleo/divDyn.qmd
                text: divDyn
              - file: software/R/geo_paleo/chronosphere.qmd
                text: chronosphere
            - section: Spatial 
              contents:
              - file: software/R/spatial/icosa.qmd
                text: icosa
          - section: Python 
            file: software/python.qmd
            contents:
            - section: Geology/Paleontology
              contents:
              - file: software/python/pyGPlates.qmd
                text: pyGPlates
        - section: Ecology Apps
          file: software/R.qmd
          contents:
          - file: software/maxent.qmd
            text: Maxent
        - section: Geology Apps
          file: software/R.qmd
          contents:
          - file: software/gplates.qmd
            text: GPlates
            
    - title: "Practice"
      style: "docked"
      collapse-level: 2
      contents:
        - examples.qmd
        
format:
  html:
    theme:
    - zephyr
    - custom.scss
    css: styles.css


resources:
 - CNAME
