<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.302">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kocsis, Adam">

<title>Evolv-ED - Basic diversity dynamics of scleractinian corals with divDyn</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-listing/list.min.js"></script>
<script src="../../../site_libs/quarto-listing/quarto-listing.js"></script>
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>

  window.document.addEventListener("DOMContentLoaded", function (_event) {
    const listingTargetEl = window.document.querySelector('#listing-resources .list');
    if (!listingTargetEl) {
      // No listing discovered, do not attach.
      return; 
    }

    const options = {
      valueNames: ['listing-title','listing-path','listing-type',{ data: ['index'] },{ data: ['categories'] }],
      
      searchColumns: ["listing-title","listing-path","listing-type"],
    };

    window['quarto-listings'] = window['quarto-listings'] || {};
    window['quarto-listings']['listing-resources'] = new List('listing-resources', options);

    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  });

  window.addEventListener('hashchange',() => {
    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  })
  </script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../images/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Evolv-ED</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../../why.html" rel="" target="">
 <span class="dropdown-text">Why?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../team.html" rel="" target="">
 <span class="dropdown-text">Contributors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../material.html" rel="" target="">
 <span class="dropdown-text">The Material</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../../databases.html" rel="" target="">
 <span class="menu-text">Databases</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../software.html" rel="" target="">
 <span class="menu-text">Software</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../examples.html" rel="" target="">
 <span class="menu-text">Practice</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-contribute" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Contribute!</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-contribute">    
        <li>
    <a class="dropdown-item" href="../../../about.html" rel="" target="">
 <span class="dropdown-text">How?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../about.html" rel="" target="">
 <span class="dropdown-text">Guide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../about.html" rel="" target="">
 <span class="dropdown-text">Get in touch!</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://integrated-record.github.io/" rel="" target="">
 <span class="menu-text">IRAL</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/integrated" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/learn_evolved" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#goals-and-introduction" id="toc-goals-and-introduction" class="nav-link active" data-scroll-target="#goals-and-introduction">Goals and introduction</a></li>
  <li><a href="#occurrence-data-download" id="toc-occurrence-data-download" class="nav-link" data-scroll-target="#occurrence-data-download">Occurrence data download</a></li>
  <li><a href="#data-processing" id="toc-data-processing" class="nav-link" data-scroll-target="#data-processing">Data processing</a>
  <ul class="collapse">
  <li><a href="#installing-and-loading-divdyn" id="toc-installing-and-loading-divdyn" class="nav-link" data-scroll-target="#installing-and-loading-divdyn">Installing and loading divDyn</a></li>
  <li><a href="#initial-filtering" id="toc-initial-filtering" class="nav-link" data-scroll-target="#initial-filtering">Initial filtering</a></li>
  <li><a href="#stratigraphic-resolution" id="toc-stratigraphic-resolution" class="nav-link" data-scroll-target="#stratigraphic-resolution">Stratigraphic resolution</a></li>
  </ul></li>
  <li><a href="#sampling-assessment" id="toc-sampling-assessment" class="nav-link" data-scroll-target="#sampling-assessment">Sampling assessment</a>
  <ul class="collapse">
  <li><a href="#plotting" id="toc-plotting" class="nav-link" data-scroll-target="#plotting">Plotting</a></li>
  </ul></li>
  <li><a href="#richness-through-time" id="toc-richness-through-time" class="nav-link" data-scroll-target="#richness-through-time">Richness through time</a>
  <ul class="collapse">
  <li><a href="#subsampling" id="toc-subsampling" class="nav-link" data-scroll-target="#subsampling">Subsampling</a>
  <ul class="collapse">
  <li><a href="#classical-rarefaction" id="toc-classical-rarefaction" class="nav-link" data-scroll-target="#classical-rarefaction">Classical Rarefaction</a></li>
  <li><a href="#shareholder-quorum-subsampling-sqs" id="toc-shareholder-quorum-subsampling-sqs" class="nav-link" data-scroll-target="#shareholder-quorum-subsampling-sqs">Shareholder Quorum Subsampling (SQS)</a></li>
  </ul></li>
  <li><a href="#turnover-rates" id="toc-turnover-rates" class="nav-link" data-scroll-target="#turnover-rates">Turnover rates</a></li>
  </ul></li>
  <li><a href="#symbiotic-status-effect-on-diversity-dynamics" id="toc-symbiotic-status-effect-on-diversity-dynamics" class="nav-link" data-scroll-target="#symbiotic-status-effect-on-diversity-dynamics">Symbiotic status’ effect on diversity dynamics</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    <div class="quarto-margin-footer"><div class="margin-footer-item">
<p><a href="https://www.evolv-ed.net/"> <img src="../../../../../../images/logo.png" width="100"> </a></p>
</div></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Basic diversity dynamics of scleractinian corals with divDyn</h1>
<p class="subtitle lead">A basic introduction to the divDyn package</p>
  <div class="quarto-categories">
    <div class="quarto-category">extinction</div>
    <div class="quarto-category">origination</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p><a href="../../../adam_kocsis.html">Kocsis, Adam</a> </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div id="listing-resources" class="quarto-listing quarto-listing-container-custom">
<p><a href="../../../software/R/geo_paleo/divDyn.html"><span class="badge rounded-pill bg-primary">divDyn</span></a> <a href="../../../databases/pbdb.html"><span class="badge rounded-pill bg-primary">pbdb</span></a> <a href="../../../software/R/geo_paleo/chronosphere.html"><span class="badge rounded-pill bg-primary">chronosphere</span></a> <a href="../../../software/R.html"><span class="badge rounded-pill bg-primary">R</span></a></p>
<div class="listing-no-matching d-none">
No matching items
</div>
</div>
<section id="goals-and-introduction" class="level1">
<h1>Goals and introduction</h1>
<p>The purpose of this vignette is to guide new users through data acquisition and analysis, as well as to demonstrate the basic capabilities of the divDyn R <span class="citation" data-cites="kocsis2019package">(<a href="#ref-kocsis2019package" role="doc-biblioref">Kocsis et al. 2019</a>)</span> package. This tutorial will use Scleractininan corals as an example group which was selected selected because the due to data quality reasons and as we have readily available additional information about the coral taxa with which to customize the analyses.</p>
</section>
<section id="occurrence-data-download" class="level1">
<h1>Occurrence data download</h1>
<p>To run analyses, first the occurrence data have to be downloaded and processed. You can download all PBDB occurrences using the <code>chronosphere</code> R package. The <code>chronosphere</code> is an initiative we have started at GeoZentrum Nordbayern in Erlangen, to facilitate the use, tracability, portability and version controlling of data in scientific analyses.</p>
<p>The package is available from the CRAN repositories and can be installed with the following line of code (you will probably have to select your preferred download mirror).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"chronosphere"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After the package is installed, it is ready for use, you can attach it with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(chronosphere)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: raster</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: sp</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">fetch</span>(<span class="st">"pbdb"</span>, <span class="at">ver=</span><span class="st">"20220510"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>If you use the data in publications, please cite its
reference(s), as well as that of the 'chronosphere' package.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Please remember to acknowledge the Paleobiology Database (http://paleobiodb.org) in your publication.</code></pre>
</div>
</div>
<p>This is a pre-processed version of the PBDB that was downloaded with this API call:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(dat)<span class="sc">$</span>chronosphere<span class="sc">$</span>API</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "https://paleobiodb.org/data1.2/occs/list.csv?datainfo&amp;rowcount&amp;interval=Ediacaran,Holocene&amp;show=class,classext,genus,subgenus,coll,coords,loc,paleoloc,strat,stratext,lith,env,ref,crmod,timebins,timecompare,refattr,entname,attr,ident,img,plant,abund,ecospace,taphonomy,etbasis,pres,prot,lithext,geo,methods,resgroup,refattr,ent"</code></pre>
</div>
</div>
<p>You can copy and paste this URL to your browser and the PBDB would compile the current corresponding dataset for you. It normally takes about 15-30 minutes to get the dataset, another couple of minutes to download the .csv, which you still have to read in using <code>read.table()</code>.</p>
<p>The PBDB API allows much more flexible download, but this denormalized version of the PBDB is enough for the overwhelming majority of the analyses. There are some cases, when the data you are interested in are not in this subset and you have to use the API yourself.</p>
</section>
<section id="data-processing" class="level1">
<h1>Data processing</h1>
<section id="installing-and-loading-divdyn" class="level2">
<h2 class="anchored" data-anchor-id="installing-and-loading-divdyn">Installing and loading divDyn</h2>
<p>To process the stratigraphic information in the downloaded occurrence file, and do the analyses, you have to to install and attach the divDyn package.</p>
<p>The package is available from the CRAN repositories and can be installed with the following line of code (you will probably have to select your preferred download mirror).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"divDyn"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After the package is installed, it is ready for use, you can attach it with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(divDyn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>v0.8.2. See latest changes with 'news(package="divDyn")'. Default: 
Time flows forward with 'bin', and backward with 'age' and 'slice()'.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'divDyn'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:chronosphere':

    matchtime</code></pre>
</div>
</div>
</section>
<section id="initial-filtering" class="level2">
<h2 class="anchored" data-anchor-id="initial-filtering">Initial filtering</h2>
<p>The downloaded dataset needs to be subsetted to represent the order of scleractinian corals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat[dat<span class="sc">$</span>order<span class="sc">==</span><span class="st">"Scleractinia"</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The analyses will be conducted at the level of genera.</p>
<p>The entries that have no valid genus names in the PaleoDB can be omitted at this stage. They will not provide us any information about the evolution of the group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># omit non-genus entries</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span> dat[<span class="sc">!</span>dat<span class="sc">$</span>genus<span class="sc">==</span><span class="st">""</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The dataset should be cleaned as much as possible at this stage, for didactic purposes and for keeping things simple, this step is skipped in this tutorial.</p>
</section>
<section id="stratigraphic-resolution" class="level2">
<h2 class="anchored" data-anchor-id="stratigraphic-resolution">Stratigraphic resolution</h2>
<p>Every colleciton in the the PaleoDB has a user entered <code>'early_interval'</code> and <code>'late_interval'</code> field. These are fields are used to place the collection in stratigraphy/geological time. The <code>'early_interval'</code> collection is mandatory for every entry while the <code>'late_interval'</code> is only necessary if the taxon does not fit in the interval specified as <code>'early_interval'</code>. Otherwise the <code>'late_interval'</code> field is blank (empty quotes: <code>""</code>).</p>
<p>The divDyn package uses two frequently used, discrete time scales that we use as the finest stratiigraphic resolution of our analyses: the stage level time scale (<code>stages</code>, 95 bins) and the ten million year time scale (<code>tens</code>, 49 bins). These can be attached with the <code>data()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(stages)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(tens)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These will be useful for plotting as they contain the age estimates for the intervals, but they are not too useful for finding which interval the <code>'early_interval'</code> and <code>'late_interval'</code> fields point to. This can be found in the <code>keys</code> object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(keys)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This list is designed to be used with the <code>categorize()</code> function of the package, that combines the large number of entries to and replaces them with the name of the group they belong to. This has to be run on both the <code>'early_interval'</code> and the <code>'late_interval'</code> fields.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the 'stg' entries (lookup)</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>stgMin <span class="ot">&lt;-</span> <span class="fu">categorize</span>(dat[ ,<span class="st">"early_interval"</span>], keys<span class="sc">$</span>stgInt)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>stgMax <span class="ot">&lt;-</span> <span class="fu">categorize</span>(dat[ ,<span class="st">"late_interval"</span>], keys<span class="sc">$</span>stgInt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The output of this function is either an interval number that corresponds to the <code>stages</code> timescale, <code>-1</code>, indicating that the value was empty quotes, or <code>NA</code>, if the interval is either not in the lookup table or is too broad.</p>
<p>Because this scheme is designed for general use, the output of this function is a vector of character values. These have to be demoted to numeric values, otherwise their order would not be correct.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert to numeric</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  stgMin <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stgMin)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  stgMax <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stgMax)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now these two vectors have to be combined. There are more solutions to solve the problem of stratigraphic uncertainty, but for the sake of simplicity, let’s just omit every occurrence that cannot be assigned to a single stage in the <code>stages</code> timescale. For that, we will create an empty container, check whether an the interval entry for the occurrence satisfies the condition above, and if so, save the interval ID.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># empty container</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>stg <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="fu">nrow</span>(dat))</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># select entries, where</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>stgCondition <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># the early and late interval fields indicate the same stg</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">which</span>(stgMax<span class="sc">==</span>stgMin),</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co"># or the late_intervar field is empty</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">which</span>(stgMax<span class="sc">==-</span><span class="dv">1</span>))</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="co"># in these entries, use the stg indicated by the early_interval</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  dat<span class="sc">$</span>stg[stgCondition] <span class="ot">&lt;-</span> stgMin[stgCondition] </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now every occurrence entry either has a single integer number in the <code>stg</code> column, or <code>NA</code> as its interval identifier. Note that the code above cannot be used for Cambrian and Ordovician occurrences due to stratigraphic problems. If you are interested in assigning these to stage-level intervals, we recommend to take a look at the vignette we wrote that describes global marine, Phanerozoic scale analyses:</p>
<pre><code>https://github.com/divDyn/ddPhanero/blob/master/doc/1.0.1/dd_phanero.pdf</code></pre>
<p>The assignments can be repeated for the 10-million year bins with the following commands:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a. categorize interval names to bin numbers</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># categorize is the new function of the package</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  binMin<span class="ot">&lt;-</span><span class="fu">categorize</span>(dat[,<span class="st">"early_interval"</span>],keys<span class="sc">$</span>binInt)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  binMax<span class="ot">&lt;-</span><span class="fu">categorize</span>(dat[,<span class="st">"late_interval"</span>],keys<span class="sc">$</span>binInt)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># convert to numeric</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  binMin<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(binMin)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  binMax<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(binMax)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co"># b. resolve max-min interval uncertainty</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="co"># final variable (empty)</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  dat<span class="sc">$</span>bin <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="fu">nrow</span>(dat))</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co"># use entries, where</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  binCondition <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the early and late interval fields indicate the same bin</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">which</span>(binMax<span class="sc">==</span>binMin),</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># or the late_interval field is empty</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">which</span>(binMax<span class="sc">==-</span><span class="dv">1</span>))</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="co"># in these entries, use the bin indicated by the early_interval</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  dat<span class="sc">$</span>bin[binCondition] <span class="ot">&lt;-</span> binMin[binCondition]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="sampling-assessment" class="level1">
<h1>Sampling assessment</h1>
<p>You can assess how well the stratigraphic resolution turned out by running the <code>table()</code> function on the interval-identifier vector:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(dat<span class="sc">$</span>stg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  49   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68 
   5  114   72  446  910  600  101   86  220   80   87  491  383  231 1953 1149 
  69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84 
 988  157  288  207  483 1025  389  529  124   71  158  294  745  377  311  235 
  85   86   87   88   89   90   91   92   93   94   95 
 225  458  656  519 1127 1818 1184 1463 1903 7825 1201 </code></pre>
</div>
</div>
<p>Summing it tells us how many of the overall occurrences we can assign to stratigraphic stages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">table</span>(dat<span class="sc">$</span>stg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31688</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># which is a</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">table</span>(dat<span class="sc">$</span>stg))<span class="sc">/</span><span class="fu">nrow</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8528826</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># proportion of the total data.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As we cannot use unresolved occurrences in any way, coding will be easier if we omit them at this stage.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># omit unbinned</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>dats <span class="ot">&lt;-</span> dat[<span class="sc">!</span><span class="fu">is.na</span>(dat<span class="sc">$</span>stg),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you take a look at the stage object, you can notice that besides the few entries in stages <code>37</code>, <code>49</code> and <code>50</code>, Scleractinian become important fossils in the Anisian stage.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># omit Paleozoic</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>dats <span class="ot">&lt;-</span> dats[dats<span class="sc">$</span>stg<span class="sc">&gt;</span><span class="dv">52</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can get a more organized view of sampling parameters by running the <code>binstat()</code> function in divDyn, that calculates the occurrence, collection, and reference counts in a single line. This is the general use of the high-level function of the package: you state the occurrence <code>data.frame</code> as the first, and then the column names as additional arguments. The column <code>tax</code> stands for the taxon names, <code>bin</code> for the discrete time bins, <code>coll</code> for collection identifiers and <code>ref</code> for reference identifiers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>bsFull <span class="ot">&lt;-</span> <span class="fu">binstat</span>(dats, <span class="at">tax=</span><span class="st">"genus"</span>, <span class="at">bin=</span><span class="st">"stg"</span>, </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">coll=</span><span class="st">"collection_no"</span>, <span class="at">ref=</span><span class="st">"reference_no"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>The database contains duplicate occurrences (multiple species/genus).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>bsFull<span class="sc">$</span>occs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
[16]   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
[31]   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
[46]   NA   NA   NA   NA   NA   NA   NA   NA  114   72  446  910  600  101   86
[61]  220   80   87  491  383  231 1953 1149  988  157  288  207  483 1025  389
[76]  529  124   71  158  294  745  377  311  235  225  458  656  519 1127 1818
[91] 1184 1463 1903 7825 1201</code></pre>
</div>
</div>
<p>This output is organizes so that the index of the values in the vector match up the bin identifier (e.g.&nbsp;60th value is for stg <code>60</code>). The default setting of the function will output a message about duplicate occurrences. This warns us that there are collections with more than one genus entries in a collection (i.e.&nbsp;more than one species/genus). If you are interested in genus-level analyses, it is probably better to count these as one, which you can do with <code>duplicates=FALSE</code> option.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>bs <span class="ot">&lt;-</span> <span class="fu">binstat</span>(dats, <span class="at">tax=</span><span class="st">"genus"</span>, <span class="at">bin=</span><span class="st">"stg"</span>, </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">coll=</span><span class="st">"collection_no"</span>, <span class="at">ref=</span><span class="st">"reference_no"</span>, <span class="at">duplicates=</span><span class="cn">FALSE</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>bs<span class="sc">$</span>occs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
[16]   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
[31]   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
[46]   NA   NA   NA   NA   NA   NA   NA   NA   99   66  355  769  442   77   72
[61]  201   77   74  411  291  206 1663  906  701  126  243  190  387  824  348
[76]  448  115   63  146  224  632  341  271  217  192  407  508  410  908 1207
[91]  954 1117 1474 6154  972</code></pre>
</div>
</div>
<section id="plotting" class="level2">
<h2 class="anchored" data-anchor-id="plotting">Plotting</h2>
<p>Plotting these variables is probably better then just looking at the numbers. The package includes a powerful time-scale plotting function that lets you visualize the how time is broken down to discrete intervals. This highly-customizable function is built on the basic <code>plot()</code> function, and most of its arguments are inherited. The following function call will draw plot with in the past 250 million years, with series-level shading and system-level boxes at the bottom:</p>
<div class="cell" data-plot="true">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tsplot</span>(stages, <span class="at">boxes=</span><span class="st">"sys"</span>, <span class="at">boxes.col=</span><span class="st">"systemCol"</span>, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">shading=</span><span class="st">"series"</span>, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">250</span>, <span class="dv">0</span>), <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="scleractinian-tutorial_chronos_files/figure-html/basePlot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The you can draw the number of occurrences with <code>lines()</code>. As the same row indices in the stages object and the result of <code>binstat()</code> indicate values that belong to the same interval, you do not need any subsetting to align the to data.frames.</p>
<div class="cell" data-plot="true">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tsplot</span>(stages, <span class="at">boxes=</span><span class="st">"sys"</span>, <span class="at">boxes.col=</span><span class="st">"systemCol"</span>, </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">shading=</span><span class="st">"series"</span>, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">250</span>, <span class="dv">0</span>), <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2000</span>), <span class="at">ylab=</span><span class="st">"Number occurrences"</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, bs<span class="sc">$</span>occs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="scleractinian-tutorial_chronos_files/figure-html/basePlotLine-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We will mostly use the same basic function call for plotting, and typing all these arguments is time consuming. But we can spare some time, if we defined a wrapper function around the plotting that executes the plotting call the with the same arguments that we want to keep the same, while allowing us to change what we would like to change. This is fairly straightforward with the <code>...</code> argument that allows you to pass arguments through function calls.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>tp <span class="ot">&lt;-</span> <span class="cf">function</span>(...) <span class="fu">tsplot</span>(stages, <span class="at">boxes=</span><span class="st">"sys"</span>, <span class="at">boxes.col=</span><span class="st">"systemCol"</span>, </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">shading=</span><span class="st">"series"</span>, <span class="at">xlim=</span><span class="dv">52</span><span class="sc">:</span><span class="dv">95</span>, ...)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, every time you call the newly defined function <code>tp()</code> it will have the same colour, shading and x-interval, while you can change other arguments of the <code>tsplot()</code> function. For instance if you wanted see how the number of collections change over time, you can draw a similar plot as above, with:</p>
<div class="cell" data-plot="true">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tp</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">350</span>), <span class="at">ylab=</span><span class="st">"Number of collections"</span>) </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(stages<span class="sc">$</span>mid, bs<span class="sc">$</span>colls)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="scleractinian-tutorial_chronos_files/figure-html/collPlot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The nicest feature of this function is that you do not have to use the built-in data, you can create your own timescale, as long as you use the same structure as in stages and specify the top and bottom boundaries of the intervals (top and bottom columns).</p>
<p>It is not surprising that occurrences and collection numbers have the same overall trajectory. As you can see, the sampling of corals is highly volatile over time, with a couple of marked peaks in the late Triassic, Late Jurassic, mid and Late Creteacoues and the Neogene, that we have to take into consideration in some form, when describing the evolution of the group.</p>
</section>
</section>
<section id="richness-through-time" class="level1">
<h1>Richness through time</h1>
<p>Now that we know how sampling changed over time, we can calculate a lot of diversity, extinction and origination rate series from the dataset with the basic <code>divDyn()</code> function. This function requires an occurrence dataset with a taxon (<code>tax</code>) and a discrete time (<code>bin</code>) columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">divDyn</span>(dats, <span class="at">tax=</span><span class="st">"genus"</span>, <span class="at">bin=</span><span class="st">"stg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The output of this function resembles that of the binstat() function. Variables are organized with their names. - Names starting with t- (e.g.&nbsp;t3) are taxon counts - Names starting with div- are diversity estimators. - Names starting with ori- and ext- are origination and extinction rate estimators, respectively. - Names starting with samp- are measures of sampling completeness. The abbreviations are resolved in the help file that can be accessed with</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>?divDyn</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This file also includes all equations that are used to calculate the variables.</p>
<p>The most basic way to count richness over time is with range-through diversities (<code>divRT</code>). This is simply just the count of taxa that was supposed to be living in an interval (assuming presence if it was found before and after it, if it is not sampled). You can plot these with:</p>
<div class="cell" data-plot="true">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># simple diversity</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tp</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">300</span>), <span class="at">ylab=</span><span class="st">"richness"</span>)    </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(stages<span class="sc">$</span>mid, dd<span class="sc">$</span>divRT, <span class="at">lwd=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="scleractinian-tutorial_chronos_files/figure-html/divRT-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This is the metric that can be applied to Sepkoski’s compendium <span class="citation" data-cites="sepkoski_compendium_2002">(<a href="#ref-sepkoski_compendium_2002" role="doc-biblioref">Sepkoski 2002</a>)</span>. Note that diversity in the Cretaceous is comparable to those that corals demonstrated in the Neogene, with a slight decrease in the Cretaecous. The sharp drop in the last bin is also worthy of notion. This is an edge effect and is also partially present because the fossil information in the Holocene is usually worse in the PaleoDB. However, adding all recent taxa to the dataset would also create an artifact known as the Pull of the Recent. The complete preservation would spuriously increase range-based diversity estimates in the last few bins.</p>
<section id="subsampling" class="level2">
<h2 class="anchored" data-anchor-id="subsampling">Subsampling</h2>
<p>Ultimately, all time series of richness suffer from the heterogeneity of sampling in space and time, as well as a number of other factors. For instance, the temporal bias is clear, as there is a high correlation between sampling and richness through time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(dd<span class="sc">$</span>divRT, bs<span class="sc">$</span>occs, <span class="at">method=</span><span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(dd$divRT, bs$occs, method = "spearman"): Cannot
compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  dd$divRT and bs$occs
S = 6167.7, p-value = 0.0007426
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.5002229 </code></pre>
</div>
</div>
<p>Subsampling aims at estimating what values the focus variables would take, if sampling were uniform over time. This methodology was developed for richness estimation (in an analytical context first, i.e.&nbsp;algegra and equations and then with Monte Carlo simulations), but can be generalized to other variables. You are invited to check out this generalization in the package Handout that you can access with the</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vignette</span>(<span class="st">"handout"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>command.</p>
<section id="classical-rarefaction" class="level3">
<h3 class="anchored" data-anchor-id="classical-rarefaction">Classical Rarefaction</h3>
<p>As all intervals have sampling at least 50 occurrences, let’s start with rarefying every stage to <code>50</code> occurrences. You can accomplish this by running:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>cr50 <span class="ot">&lt;-</span> <span class="fu">subsample</span>(dats, <span class="at">tax=</span><span class="st">"genus"</span>, <span class="at">bin=</span><span class="st">"stg"</span>, </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">q=</span><span class="dv">50</span>, <span class="at">coll=</span><span class="st">"collection_no"</span>, <span class="at">duplicates=</span><span class="cn">FALSE</span>, <span class="at">iter=</span><span class="dv">300</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This function call will run the default Classical Rarefaction method on every interval <code>300</code> times, calculate the entire divDyn output matrix in every trial and averages the results. With specifying <code>coll=collection_no</code> and <code>duplicates=FALSE</code>, we instruct the function to treat the multiple occurrences of the same genus in a collection as one. It’s structure is the same as that of <code>divDyn()</code>’s, so you can access the variables the same way.</p>
<div class="cell" data-plot="true">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tp</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>), <span class="at">ylab=</span><span class="st">"Subsampled richness"</span>)   </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, cr50<span class="sc">$</span>divRT, <span class="at">lwd=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="scleractinian-tutorial_chronos_files/figure-html/subDiv-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>That is a different overall picture. Note the much higher peak in the Cretaceous then before.You can also note the low variation of the series. This is an artifact of using classical rarefaction on the data: as the quota drops the curces get flatter and flatter. This is the primary reason why Shareholder Quorum Subsamping was developed (Alroy, 2010).</p>
</section>
<section id="shareholder-quorum-subsampling-sqs" class="level3">
<h3 class="anchored" data-anchor-id="shareholder-quorum-subsampling-sqs">Shareholder Quorum Subsampling (SQS)</h3>
<p>SQS is the algorithmic solution that tries to subsample the data to an equal coverage. Coverage is just frequency of the taxon of total sampling pool, which is desired to be constant in the whole series. The detailed understanding of what SQS is doing and how is unfortunately out of scope of this tutorial, but its detail scan be found in J. Alroy’ paper in Science <span class="citation" data-cites="alroy_shifting_2010">(<a href="#ref-alroy_shifting_2010" role="doc-biblioref">Alroy 2010</a>)</span>.</p>
<p>Instead of a quota, SQS requires a quorum, a target coverage. This quorum is dependent on the taxon coverage estimation process used in the algorithm. A too high quorum will result in missing information from the time bin. You can run the basic SQS by running.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>sqsDD <span class="ot">&lt;-</span> <span class="fu">subsample</span>(dats, <span class="at">tax=</span><span class="st">"genus"</span>, <span class="at">bin=</span><span class="st">"stg"</span>, <span class="at">q=</span><span class="fl">0.5</span>, <span class="at">type=</span><span class="st">"sqs"</span>,</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">duplicates=</span><span class="cn">FALSE</span>, <span class="at">coll=</span><span class="st">"collection_no"</span>, <span class="at">iter=</span><span class="dv">300</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then you can plot the results with.</p>
<div class="cell" data-plot="true">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tp</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>), <span class="at">ylab=</span><span class="st">"Subsampled richness (SQS, 0.5)"</span>)    </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, sqsDD<span class="sc">$</span>divRT, <span class="at">lwd=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="scleractinian-tutorial_chronos_files/figure-html/subDivSQS-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This is a much more accurate depiction of diversity but we still do not know much about the diversity trajectory in the Neogene. Luckily there are estimators that are not biased by this effects. Sampled-in-bin diversities (<code>divSIB</code>) are only influenced by sampling within the interval of focus, but they have to be corrected for sampling too. Luckily this is not imporant issue, as there are estimators that are not biased by this effects. Sampled-in-bin diversities (<code>divSIB</code>) are only influenced by sampling within the interval of focus, which we can also calculate with gap analysis of the record (i.e.&nbsp;how many taxa are sampled immediately before and after the focal interval but in it). This metric is known as the Corrected Sampled-In-Bin diversity (<code>divCSIB</code>), which is recommended for general use.</p>
<p>The likely trajectory of coral diveristy through time is then:</p>
<div class="cell" data-plot="true">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tp</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">80</span>), <span class="at">ylab=</span><span class="st">"Subsampled richness (SQS, 0.5)"</span>) </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, sqsDD<span class="sc">$</span>divCSIB, <span class="at">lwd=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="scleractinian-tutorial_chronos_files/figure-html/subCSIB-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>includes a huge peak in the Cretaceous.</p>
</section>
</section>
<section id="turnover-rates" class="level2">
<h2 class="anchored" data-anchor-id="turnover-rates">Turnover rates</h2>
<p>We can get more information about what guided the taxon’s history through time by looking at the temporal trajectories of turnover. The main <code>divDyn()</code> function output includes turnover these rates. You can plot the per capita extinction and origination rates of Foote <span class="citation" data-cites="foote_morphological_1999">(<a href="#ref-foote_morphological_1999" role="doc-biblioref">Foote 1999</a>)</span> with the following lines of code:</p>
<div class="cell" data-plot="true">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># turnover rates</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tp</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">ylab=</span><span class="st">"per capita turnover rates"</span>)   </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, dd<span class="sc">$</span>extPC, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, dd<span class="sc">$</span>oriPC, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"green"</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">"extinction"</span>, <span class="st">"origination"</span>), </span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">col=</span><span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>), <span class="at">lwd=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="scleractinian-tutorial_chronos_files/figure-html/turn-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Note huge peaks at the ends of the series (origination rates peak at the beginning and extinction rates at the recent end). These are edge effects that are force due to the dataset structure. You can note the effects of the end-Triassic, Pliensbachian-Toarcian and the end-Cretaceous crises on the rates. Subsampling typically has a much lower effect on turnover rates, but it is helpful to validate patterns that you see with the raw data. Although this has has to be assessed in more detail J. Alroy recommended to use Classical Rarefaction for the estimation of turnover rates.</p>
</section>
</section>
<section id="symbiotic-status-effect-on-diversity-dynamics" class="level1">
<h1>Symbiotic status’ effect on diversity dynamics</h1>
<p>Story gets more interesting when the difference between different symbiotic types are considered. Zooxanthellate (Z) and Azooxanthellate (AZ) corals are about equally diverse in today oceans. The two tend to differ in morphology (Z are usually colonials, while most AZ corals are solitary) and typically occupy different environments (Z corals prefer shallower reef settings, whereas AZ corals tend to occurr in deeper waters). How the distinction emerged and what the reasons for this could be is the topic of one our papers in Paleobiology <span class="citation" data-cites="kiessling_biodiversity_2015">(<a href="#ref-kiessling_biodiversity_2015" role="doc-biblioref">Kiessling and Kocsis 2015</a>)</span>, where these snippets of code come from.</p>
<p>Determining the symbotic status (whether or not they host photosymbionts) of extant corals is straightforward, but not so for fossil ones. Although the photosymbionts do not fossilize, some morphological traits and geogchemical properties correlate with the corals’ ability to host symbionts. W. Kiessling compiled a list of most likely photosymiotic status for coral genera occurring in the Paleobiology Database. This list is available from GitHub and can be loaded directly with this URL.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>sym <span class="ot">&lt;-</span> <span class="fu">fetch</span>(<span class="at">dat=</span><span class="st">"som"</span>, <span class="st">"kiessling-coralgenera"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>If you use the data in publications, please cite its
reference(s), as well as that of the 'chronosphere' package.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Kiessling, W., &amp; Kocsis, Á. T. (2015). Biodiversity dynamics and environmental occupancy of fossil azooxanthellate and zooxanthellate scleractinian corals. Paleobiology, 41(3), 402–414.</code></pre>
</div>
</div>
<p>This table also contains information about corallite integrity, coloniality, and whether the taxon is extant or extinct.</p>
<p>Every row in this table represent a coral genus in the PBDB, which is designated with in the column <code>genus.subgenus</code>. These entries were assigned to valid genus names (<code>genus.proper</code>) by Wolfgang Kiessling. It is very easy to match the two tables with the <code>merge()</code> function. Stating <code>all.x=TRUE</code> forces the keeping of all rows in the first argument, which is in our case the PaleoDB. This is handy, as we’d like to assess how many fossil genera do get phototsymbiotic tags.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># merge the two tables</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>dats <span class="ot">&lt;-</span> <span class="fu">merge</span>(dats, sym, <span class="at">by.x=</span><span class="st">"genus"</span>, <span class="at">by.y=</span><span class="st">"genus.subgenus"</span>, <span class="at">all.x=</span><span class="cn">TRUE</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># which are not merged?</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="co"># occurrences</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(dats<span class="sc">$</span>ECOLOGY))<span class="sc">/</span><span class="fu">nrow</span>(dats) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04595524</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># genera</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>genTab<span class="ot">&lt;-</span><span class="fu">unique</span>(dats[, <span class="fu">c</span>(<span class="st">"genus"</span>, <span class="st">"ECOLOGY"</span>)])</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(genTab<span class="sc">$</span>ECOLOGY))<span class="sc">/</span><span class="fu">nrow</span>(genTab) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.06451613</code></pre>
</div>
</div>
<p>The table also contains useful information about whether the taxa are extant or extinct. As there are some</p>
<p>You can calculate the diversity dynamics of these groups separately by subsetting the occurrence data to two subsets and then running the <code>divDyn()</code> function on them separately on them. As their ecology tend to be similar, the Azoxanthellate and Apozooxanthellate (non- and facultatively symbiotic) corals are analyzed together.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># subset</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>zdat <span class="ot">&lt;-</span> dats[dats<span class="sc">$</span>ECOLOGY<span class="sc">==</span><span class="st">"z"</span>, ]</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>azdat <span class="ot">&lt;-</span> dats[dats<span class="sc">$</span>ECOLOGY<span class="sc">==</span><span class="st">"az"</span> <span class="sc">|</span> dats<span class="sc">$</span>ECOLOGY<span class="sc">==</span><span class="st">"ap"</span>, ]</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="co"># divDyn</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>zDD <span class="ot">&lt;-</span> <span class="fu">divDyn</span>(zdat, <span class="at">tax=</span><span class="st">"genus"</span>, <span class="at">bin=</span><span class="st">"stg"</span>)</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>azDD <span class="ot">&lt;-</span> <span class="fu">divDyn</span>(azdat, <span class="at">tax=</span><span class="st">"genus"</span>, <span class="at">bin=</span><span class="st">"stg"</span>)   </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The difference in the diversity trajectories of the two group is striking, even with the raw patterns. You are invited to check the difference with subsampling, but as the preservation potential is similar, it is likely that subsampling won’t affect relative numbers.</p>
<div class="cell" data-plot="true">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tp</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">200</span>), <span class="at">ylab=</span><span class="st">"Raw richness"</span>)  </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, zDD<span class="sc">$</span>divRT, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, azDD<span class="sc">$</span>divRT, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"orange"</span>)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="co"># legend function</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>legZAZ <span class="ot">&lt;-</span> <span class="cf">function</span>(...) </span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">legend</span>(<span class="at">legend=</span><span class="fu">c</span>(<span class="st">"z"</span>, <span class="st">"az"</span>), <span class="at">col=</span><span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"orange"</span>), </span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">bg=</span><span class="st">"white"</span>, <span class="at">cex=</span><span class="fl">1.3</span>, ...)</span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a><span class="fu">legZAZ</span>(<span class="st">"topleft"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="scleractinian-tutorial_chronos_files/figure-html/zazdiv-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>But what about turnover? You can contrast the extinction rates of the two groups with the already calculated per-capita rates.</p>
<div class="cell" data-plot="true">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tp</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">ylab=</span><span class="st">"Per capita extinctions"</span>)  </span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="co"># lines</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, zDD<span class="sc">$</span>extPC, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, azDD<span class="sc">$</span>extPC, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"orange"</span>)</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a><span class="co"># legend</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legZAZ</span>(<span class="st">"topleft"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="scleractinian-tutorial_chronos_files/figure-html/zazext-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Overall, the two series are quite similar. Z corals appear to be somewhat more affected at the end-Cretaceous. How about originations?</p>
<div class="cell" data-plot="true">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tp</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">ylab=</span><span class="st">"Per capita originations"</span>) </span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="co"># lines</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, zDD<span class="sc">$</span>oriPC, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, azDD<span class="sc">$</span>oriPC, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"orange"</span>)</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a><span class="co"># legend</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legZAZ</span>(<span class="st">"topleft"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="scleractinian-tutorial_chronos_files/figure-html/zazori-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>But how do we know that differences are meaningful? The difference in the rates of the two group can come from two sources: random estimation error, or group membership. Estimation error will depend on the number of sampled taxa. One way to figure this out is to use the priciniples of model selection: we can compare the likelihood support of two models: whether the observed difference comes from the estimation error of a single model or there are actually two separate models that better describe the observed patterns. This principle is implemented in the fucntion <code>ratesplit()</code> that compares these two models in a single call. For this, the ECOLOGY variable has to be cleaned:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>zdat<span class="sc">$</span>ecol <span class="ot">&lt;-</span> <span class="st">"z"</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>azdat<span class="sc">$</span>ecol <span class="ot">&lt;-</span> <span class="st">"az"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then the function can be called using the new variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>rs<span class="ot">&lt;-</span><span class="fu">ratesplit</span>(<span class="fu">rbind</span>(zdat, azdat), <span class="at">sel=</span><span class="st">"ecol"</span>, <span class="at">tax=</span><span class="st">"genus"</span>, <span class="at">bin=</span><span class="st">"stg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This function compares the per capita rates that we have been working with, and the output shows the bin numbers where difference is meaningful.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>rs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$ext
[1] 66 94

$ori
[1] 75 81</code></pre>
</div>
</div>
<p>You can visualize these with dots. The results for origination rates indicate that azoxantellate corals showed bursts of evolution in some intervals.</p>
<div class="cell" data-plot="true">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tp</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">ylab=</span><span class="st">"Per capita originations"</span>) </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, zDD<span class="sc">$</span>oriPC, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, azDD<span class="sc">$</span>oriPC, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"orange"</span>)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="fu">legZAZ</span>(<span class="st">"topleft"</span>)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="co"># display selectivity with points</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a><span class="co"># select the higher rates</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>selIntervals<span class="ot">&lt;-</span><span class="fu">cbind</span>(zDD<span class="sc">$</span>oriPC[rs<span class="sc">$</span>ori], azDD<span class="sc">$</span>oriPC[rs<span class="sc">$</span>ori])</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>groupSelector<span class="ot">&lt;-</span><span class="fu">apply</span>(selIntervals, <span class="dv">1</span>, <span class="cf">function</span>(x) x[<span class="dv">1</span>]<span class="sc">&lt;</span>x[<span class="dv">2</span>])</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a><span class="co"># draw the points</span></span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(stages<span class="sc">$</span>mid[rs<span class="sc">$</span>ori[groupSelector]], azDD<span class="sc">$</span>oriPC[rs<span class="sc">$</span>ori[groupSelector]],</span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch=</span><span class="dv">16</span>, <span class="at">col=</span><span class="st">"orange"</span>, <span class="at">cex=</span><span class="dv">2</span>)</span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(stages<span class="sc">$</span>mid[rs<span class="sc">$</span>ori[<span class="sc">!</span>groupSelector]], zDD<span class="sc">$</span>oriPC[rs<span class="sc">$</span>ori[<span class="sc">!</span>groupSelector]],</span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch=</span><span class="dv">16</span>, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">cex=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="scleractinian-tutorial_chronos_files/figure-html/zazoriSel-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Extinction rate results are:</p>
<div class="cell" data-plot="true">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tp</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">ylab=</span><span class="st">"Per capita extinctions"</span>)  </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, zDD<span class="sc">$</span>extPC, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stages<span class="sc">$</span>mid, azDD<span class="sc">$</span>extPC, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"orange"</span>)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">legZAZ</span>(<span class="st">"topleft"</span>)</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="co"># display selectivity with points</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a><span class="co"># select the higher rates</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>selIntervals<span class="ot">&lt;-</span><span class="fu">cbind</span>(zDD<span class="sc">$</span>extPC[rs<span class="sc">$</span>ext], azDD<span class="sc">$</span>extPC[rs<span class="sc">$</span>ext])</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>groupSelector<span class="ot">&lt;-</span><span class="fu">apply</span>(selIntervals, <span class="dv">1</span>, <span class="cf">function</span>(x) x[<span class="dv">1</span>]<span class="sc">&lt;</span>x[<span class="dv">2</span>])</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a><span class="co"># draw the points</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(stages<span class="sc">$</span>mid[rs<span class="sc">$</span>ext[groupSelector]], azDD<span class="sc">$</span>extPC[rs<span class="sc">$</span>ext[groupSelector]],</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch=</span><span class="dv">16</span>, <span class="at">col=</span><span class="st">"orange"</span>, <span class="at">cex=</span><span class="dv">2</span>)</span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(stages<span class="sc">$</span>mid[rs<span class="sc">$</span>ext[<span class="sc">!</span>groupSelector]], zDD<span class="sc">$</span>extPC[rs<span class="sc">$</span>ext[<span class="sc">!</span>groupSelector]],</span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch=</span><span class="dv">16</span>, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">cex=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="scleractinian-tutorial_chronos_files/figure-html/zazextSel-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Note that despite the apparently higher extinction rates of Z corals, the difference in the end-Createcous mass extinction is not supported by the method. The end-Pleistocene value is likely a result of the data treatmen around the recent, but the observed difference in the late Jurassic was not significant in our prevoius study <span class="citation" data-cites="kiessling_biodiversity_2015">(<a href="#ref-kiessling_biodiversity_2015" role="doc-biblioref">Kiessling and Kocsis 2015</a>)</span>. This points to the importance of using clean data, and importance of the quick reproduction/reanalysis that the divDyn package now provides.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Alroy, J. (2010). The Shifting Balance of Diversity Among Major Marine Animal Groups. Science, 329, 1191–1194. https://doi.org/10.1126/science.1189910</p>
<p>Foote, M. (1999). Morphological Diversity In The Evolutionary Radiation Of Paleozoic and Post-Paleozoic Crinoids. Paleobiology, 25(S2), 1–115.</p>
<p>Kiessling, W., &amp; Kocsis, A. T. (2015). Biodiversity dynamics and environmental occupancy of fossil azooxanthellate and zooxanthellate scleractinian corals. Paleobiology, 41(3), 402–414.</p>
<p>Sepkoski Jr, J. J. (2002). A compendium of fossil marine animal genera. Bulletins of American Paleontology, 363, 1-560.</p>




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-alroy_shifting_2010" class="csl-entry" role="listitem">
Alroy, John. 2010. <span>“The <span>Shifting</span> <span>Balance</span> of <span>Diversity</span> <span>Among</span> <span>Major</span> <span>Marine</span> <span>Animal</span> <span>Groups</span>.”</span> <em>Science</em> 329: 1191–94. <a href="https://doi.org/10.1126/science.1189910">https://doi.org/10.1126/science.1189910</a>.
</div>
<div id="ref-foote_morphological_1999" class="csl-entry" role="listitem">
Foote, Mike. 1999. <span>“Morphological <span>Diversity</span> <span>In</span> <span>The</span> <span>Evolutionary</span> <span>Radiation</span> <span>Of</span> <span>Paleozoic</span> and <span>Post</span>-<span>Paleozoic</span> <span>Crinoids</span>.”</span> <em>Paleobiology</em> 25 (S2): 1–115. <a href="https://doi.org/10.1017/S0094837300020236">https://doi.org/10.1017/S0094837300020236</a>.
</div>
<div id="ref-kiessling_biodiversity_2015" class="csl-entry" role="listitem">
Kiessling, Wolfgang, and Ádám T. Kocsis. 2015. <span>“Biodiversity Dynamics and Environmental Occupancy of Fossil Azooxanthellate and Zooxanthellate Scleractinian Corals.”</span> <em>Paleobiology</em> 41 (3): 402–14.
</div>
<div id="ref-kocsis2019package" class="csl-entry" role="listitem">
Kocsis, Ádám T., Carl J. Reddin, John Alroy, and Wolfgang Kiessling. 2019. <span>“The <span>R</span> Package <span class="nocase">divDyn</span> for Quantifying Diversity Dynamics Using Fossil Sampling Data.”</span> <em>Methods in Ecology and Evolution</em> 10 (5): 735–43. <a href="https://doi.org/10.1111/2041-210X.13161">https://doi.org/10.1111/2041-210X.13161</a>.
</div>
<div id="ref-sepkoski_compendium_2002" class="csl-entry" role="listitem">
Sepkoski, J. J. Jr. 2002. <span>“A Compendium of Fossil Marine Animal Genera.”</span> <em>Bulletins of American Paleontology</em> 363: 1–560.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>